[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-arg=-Wl,-rpath,@loader_path", "-C", "link-arg=-Wl,-rpath,target/release", "-C", "link-arg=-Wl,-rpath,target/debug"]

[env]
DYLD_LIBRARY_PATH = { value = "target/release:target/debug", relative = true }